CREATE TABLE buildings (id SERIAL NOT NULL, name varchar(150), address_detail int4, province varchar(100), ward varchar(100), common_amenities varchar(255), latitude float8, longitude float8, "num_floors interger" int4, general_rules int4, is_active int4, created_at timestamp, updated_at timestamp, landlord_id int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE contract_services (id SERIAL NOT NULL, service_name varchar(100) NOT NULL, unit varchar(30), applied_unit_price int4, billing_method varchar(50), "last_index interger" int4, contract_id int4 NOT NULL, service_id int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE contracts (id SERIAL NOT NULL, start_date date, end_date date, rent_price int4, deposit_amount int4, payment_cycle_day int4, status varchar(30), pdf_file_url int4, terms_and_conditions varchar(500), created_at timestamp, updated_at timestamp, room_id int4 NOT NULL, tenant_id int4 NOT NULL, landlord_id int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE invoice_items (id SERIAL NOT NULL, item_name varchar(255), quantity int4, unit_price int4, amount int4, item_type varchar(255), previous_index int4, current_index int4, note varchar(255), invoice_id int4 NOT NULL, contract_service_id int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE invoices (id SERIAL NOT NULL, billing_period varchar(20), due_date date, room_price int4, services_amount int8, other_amount int8, total_amount int4, paid_amount int4, status varchar(30), payment_method varchar(30), paid_at timestamp, cancel_reason varchar(255), payment_note varchar(255), contract_id int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE notifications (id SERIAL NOT NULL, title varchar(200), content varchar(255), notification_type varchar(50), related_entity_type varchar(50), related_entity_id int4, is_read int4, created_at timestamp, deleted_at timestamp, User_id int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE room_images (id SERIAL NOT NULL, image_url varchar(255), display_order int4, created_at timestamp, deleted_at timestamp, room_id int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE Room_service (roomsid int4 NOT NULL, servicesid int4 NOT NULL);
CREATE TABLE rooms (id SERIAL NOT NULL, name varchar(100), province varchar(100), ward varchar(100), address_detail int4, floor int4, area int4, listed_price int4, standard_deposit int4, max_capacity int4, current_occupancy int4, furnishing_level varchar(50), amenities varchar(255), description int4, status varchar(30), latitude float8, longitude float8, is_public int4, created_at timestamp, updated_at timestamp, buildind_id int4 NOT NULL, landlord_id int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE services (id SERIAL NOT NULL, name varchar(100), category varchar(50), unit varchar(30), unit_price int4, billing_method varchar(50), created_at timestamp, updated_at timestamp, landlord_id int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE tenant_link_invitations (id SERIAL NOT NULL, status varchar(30), reject_reason varchar(255), responded_at timestamp, created_at timestamp, tenant_id int4 NOT NULL, User_id int4 NOT NULL, contract_id int4 NOT NULL, invited_by int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE tenants (id SERIAL NOT NULL, full_name varchar(100), phone varchar(20), id_card_number varchar(20), gender varchar(10), date_of_birth date, id_card_photo_front varchar(500), id_card_photo_back varchar(500), is_representative int4, link_status varchar(30), updated_at timestamp, created_at timestamp, contract_id int4 NOT NULL, user_id int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE "User" (id SERIAL NOT NULL, username varchar(50), password_hash varchar(255), full_name varchar(255), email varchar(255), phone varchar(255), role varchar(255), status varchar(255), locked_reason varchar(255), locked_until timestamp, avatar_url varchar(255), date_of_birth timestamp, gender varchar(255), enable int4, bio varchar(255), created_at timestamp, updated_at timestamp, PRIMARY KEY (id));
ALTER TABLE invoices ADD CONSTRAINT FKinvoices314320 FOREIGN KEY (contract_id) REFERENCES contracts (id);
ALTER TABLE contract_services ADD CONSTRAINT FKcontract_s89902 FOREIGN KEY (contract_id) REFERENCES contracts (id);
ALTER TABLE invoice_items ADD CONSTRAINT FKinvoice_it618216 FOREIGN KEY (invoice_id) REFERENCES invoices (id);
ALTER TABLE rooms ADD CONSTRAINT FKrooms71533 FOREIGN KEY (buildind_id) REFERENCES buildings (id);
ALTER TABLE room_images ADD CONSTRAINT FKroom_image445410 FOREIGN KEY (room_id) REFERENCES rooms (id);
ALTER TABLE contracts ADD CONSTRAINT FKcontracts90552 FOREIGN KEY (room_id) REFERENCES rooms (id);
ALTER TABLE invoice_items ADD CONSTRAINT FKinvoice_it727887 FOREIGN KEY (contract_service_id) REFERENCES contract_services (id);
ALTER TABLE tenants ADD CONSTRAINT FKtenants109830 FOREIGN KEY (user_id) REFERENCES "User" (id);
ALTER TABLE services ADD CONSTRAINT FKservices886683 FOREIGN KEY (landlord_id) REFERENCES "User" (id);
ALTER TABLE notifications ADD CONSTRAINT FKnotificati445057 FOREIGN KEY (User_id) REFERENCES "User" (id);
ALTER TABLE buildings ADD CONSTRAINT FKbuildings290408 FOREIGN KEY (landlord_id) REFERENCES "User" (id);
ALTER TABLE tenant_link_invitations ADD CONSTRAINT FKtenant_lin224563 FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE tenant_link_invitations ADD CONSTRAINT FKtenant_lin619960 FOREIGN KEY (User_id) REFERENCES "User" (id);
ALTER TABLE Room_service ADD CONSTRAINT FKRoom_servi566038 FOREIGN KEY (roomsid) REFERENCES rooms (id);
ALTER TABLE Room_service ADD CONSTRAINT FKRoom_servi418744 FOREIGN KEY (servicesid) REFERENCES services (id);
ALTER TABLE rooms ADD CONSTRAINT FKrooms625536 FOREIGN KEY (landlord_id) REFERENCES "User" (id);
ALTER TABLE contracts ADD CONSTRAINT FKcontracts60992 FOREIGN KEY (tenant_id) REFERENCES tenants (id);
ALTER TABLE contracts ADD CONSTRAINT FKcontracts829647 FOREIGN KEY (landlord_id) REFERENCES "User" (id);
ALTER TABLE tenant_link_invitations ADD CONSTRAINT FKtenant_lin760201 FOREIGN KEY (contract_id) REFERENCES contracts (id);
ALTER TABLE tenant_link_invitations ADD CONSTRAINT FKtenant_lin591499 FOREIGN KEY (invited_by) REFERENCES "User" (id);
ALTER TABLE contract_services ADD CONSTRAINT FKcontract_s492193 FOREIGN KEY (service_id) REFERENCES services (id);

